name: EC2 Deployment

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python virtual environment and install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r apps/www/requirements.txt

      - name: Restart FastAPI systemd service
        run: |
          sudo systemctl restart fastapi-www

      - name: Verify service is running
        run: |
          sudo systemctl status fastapi-www --no-pager
