name: Docker Image CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Start the server
        run: |
          pip install -r apps/www/requirements.txt
          python run_www.py
